[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[functions."*"]
node_bundler = "esbuild"
included_files = ["valid-tokens.json"]
blob = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
